### ISSUE TITLE
User password change in Console menu

### ISSUE THREAD

**Issue by CAQ** [TuGraph-family/tugraph-db-browser#9]
Login as admin,
控制台, 账户管理, 
when editing a user's password, we can directly enter a new password without the old one.
Expected: When admin changes his own or other's password, he should enter admin's password for verification.

Note: If changing one's own password from the top-right menu (username-修改密码), we need to enter the old one. This is the expected behavior.

**Comment by lxfu1** [comment]
Entering the old password seems reasonable.
